main: ru.velialcult.treasures.CultTreasures
api-version: 1.16
version: '${project.version}'
name: CultTreasures
website: https://discord.gg/v7vE2wdRzx
author: Nilsson03
depend:
  - CultLibrary
commands:
  culttreasures: